try {
    console.log (a)
    let a = 3
  } catch (err) {
    console.log("let must be declared")
  }